### ISSUE TITLE
Building cdds failed

### ISSUE THREAD

**Issue by PradeepKiruvale** [atolab/cdds#1]
Hi All,

I tried compiling the cdds. I am facing the below issue. Please let me know what is the issue.

-Pradeep

[  1%] Building JAR file /home/robot/RND/cdds/build/idlc/target/idlc-jar-with-dependencies.jar
[ERROR] Plugin org.antlr:antlr4-maven-plugin:4.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.antlr:antlr4-maven-plugin:jar:4.5: Could not transfer artifact org.antlr:antlr4-maven-plugin:pom:4.5 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.36.215] failed: Connection timed out (Connection timed out) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
idlc/CMakeFiles/idlc.dir/build.make:160: recipe for target 'idlc/target/idlc-jar-with-dependencies.jar' failed
make[2]: *** [idlc/target/idlc-jar-with-dependencies.jar] Error 1
CMakeFiles/Makefile2:85: recipe for target 'idlc/CMakeFiles/idlc.dir/all' failed
make[1]: *** [idlc/CMakeFiles/idlc.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eboasson** [comment]
That is an error message from the Java build tool "maven", telling you that it can't connect to the maven repository at apache.org. It looks like a network connectivity issue. (You only need to download these packages once, once downloaded you no longer need to be online.)

**Comment by DapengLan** [comment]
I had similar problem. export $Java_home to JDK 8 solved my issue.

**Comment by PradeepKiruvale** [comment]
Thanks Dapeng, I will have a look.

Regards,
Pradeep
