### ISSUE TITLE
Building cdds fails - unknown types errors

### ISSUE THREAD

**Issue by siot-giovanni-rigazzi** [atolab/cdds#2]
C compiler identification: GNU 5.4.0
Maven version: "3.5.2",
Java versuib: 1.8.0.171
Ubuntu 16.04

Note: last working commit has hash: 789364d3c147ab8d2f3878345806bc88cd92becd

$make
...
Scanning dependencies of target ddsc
[ 26%] Building C object core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_ser.c.o
[ 26%] Building C object core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_ssl.c.o
[ 27%] Building C object core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_tcp.c.o
[ 28%] Building C object core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_tran.c.o
[ 29%] Building C object core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_udp.c.o
[ 29%] Building C object core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_raweth.c.o
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:47:8: error: unknown type name ‘pa_uint32_t’
 static pa_uint32_t init_g = PA_UINT32_INIT(0);
        ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:47:29: warning: implicit declaration of function ‘PA_UINT32_INIT’ [-Wimplicit-function-declaration]
 static pa_uint32_t init_g = PA_UINT32_INIT(0);
                             ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:47:29: error: initializer element is not constant
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘ddsi_raweth_conn_read’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:75:3: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
   memset (&msghdr, 0, sizeof (msghdr));
   ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:75:3: warning: incompatible implicit declaration of built-in function ‘memset’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:75:3: note: include ‘<string.h>’ or provide a declaration of ‘memset’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:94:7: warning: implicit declaration of function ‘memcpy’ [-Wimplicit-function-declaration]
       memcpy(srcloc->address + 10, src.sll_addr, 6);
       ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:94:7: warning: incompatible implicit declaration of built-in function ‘memcpy’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:94:7: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘ddsi_raweth_conn_write’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:127:3: warning: implicit declaration of function ‘assert’ [-Wimplicit-function-declaration]
   assert(niov <= INT_MAX);
   ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:128:3: warning: incompatible implicit declaration of built-in function ‘memset’
   memset (&dstaddr, 0, sizeof (dstaddr));
   ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:128:3: note: include ‘<string.h>’ or provide a declaration of ‘memset’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:133:3: warning: incompatible implicit declaration of built-in function ‘memcpy’
   memcpy(dstaddr.sll_addr, dst->address + 10, 6);
   ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:133:3: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘ddsi_raweth_conn_locator’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:186:5: warning: incompatible implicit declaration of built-in function ‘memcpy’
     memcpy(loc->address, gv.extloc.address, sizeof (loc->address));
     ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:186:5: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘ddsi_raweth_create_conn’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:198:49: error: ‘FALSE’ undeclared (first use in this function)
   bool mcast = (bool) (qos ? qos->m_multicast : FALSE);
                                                 ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:198:49: note: each undeclared identifier is reported only once for each function it appears in
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:215:3: warning: incompatible implicit declaration of built-in function ‘memset’
   memset(&addr, 0, sizeof(addr));
   ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:215:3: note: include ‘<string.h>’ or provide a declaration of ‘memset’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘joinleave_asm_mcgroup’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:261:3: warning: incompatible implicit declaration of built-in function ‘memcpy’
   memcpy(mreq.mr_address, mcloc + 10, 6);
   ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:261:3: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘ddsi_raweth_address_from_string’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:318:3: warning: incompatible implicit declaration of built-in function ‘memset’
   memset (loc->address, 0, sizeof (loc->address));
   ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:318:3: note: include ‘<string.h>’ or provide a declaration of ‘memset’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘ddsi_raweth_deinit’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:340:7: warning: implicit declaration of function ‘pa_dec32_nv’ [-Wimplicit-function-declaration]
   if (pa_dec32_nv(&init_g) == 0) {
       ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘ddsi_raweth_enumerate_interfaces’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:364:5: warning: implicit declaration of function ‘strncpy’ [-Wimplicit-function-declaration]
     strncpy(f->name, ifa->ifa_name, sizeof(f->name));
     ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:364:5: warning: incompatible implicit declaration of built-in function ‘strncpy’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:364:5: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:369:5: warning: incompatible implicit declaration of built-in function ‘memcpy’
     memcpy(x, ifa->ifa_addr, sizeof (*x));
     ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:369:5: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:374:7: warning: incompatible implicit declaration of built-in function ‘memset’
       memset(x, 0, sizeof(*x));
       ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:374:7: note: include ‘<string.h>’ or provide a declaration of ‘memset’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:379:7: warning: incompatible implicit declaration of built-in function ‘memset’
       memset(x, 0, sizeof(*x));
       ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:379:7: note: include ‘<string.h>’ or provide a declaration of ‘memset’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c: In function ‘ddsi_raweth_init’:
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:388:7: warning: implicit declaration of function ‘pa_inc32_nv’ [-Wimplicit-function-declaration]
   if (pa_inc32_nv(&init_g) == 1) {
       ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:389:5: warning: incompatible implicit declaration of built-in function ‘memset’
     memset (&ddsi_raweth_factory_g, 0, sizeof (ddsi_raweth_factory_g));
     ^
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:389:5: note: include ‘<string.h>’ or provide a declaration of ‘memset’
/home/giovanni/src/cdds/src/core/ddsi/src/ddsi_raweth.c:394:40: error: ‘TRUE’ undeclared (first use in this function)
     ddsi_raweth_factory_g.m_connless = TRUE;
                                        ^
core/CMakeFiles/ddsc.dir/build.make:210: recipe for target 'core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_raweth.c.o' failed
make[2]: *** [core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_raweth.c.o] Error 1
CMakeFiles/Makefile2:274: recipe for target 'core/CMakeFiles/ddsc.dir/all' failed
make[1]: *** [core/CMakeFiles/ddsc.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eboasson** [comment]
Fixed with apologies. Note to self: always verify building on Linux before pushing ...
