### ISSUE TITLE
Type info doesn't seem to be compatible with Connext implementation

### ISSUE THREAD

**Issue by spiderkeys** [atolab/cdds#4]
Not sure if this is just a compatibility issue between vendors, but I tried to inspect Topics, Datareaders, and Datawriters from the CDDS example applications, as well as the Python Flexy-type entities, in RTI Admin Console, and was not able to inspect their type information or subscribe to the topics in the same way that I generally can with other implementations, such as FastRTPS.

I can see the entities themselves, and the names of the types, but it just doesn't seem to get the type information correctly. I built and ran these examples on a Raspberry Pi 3, and had no issues with the functionality of the apps between each other (such as running ping/pong or the python writer/reader example).

I'm wondering if there might be some missing information at the RTPS level. Totally acknowledge that it could also be an issue on the Admin Console side! Haven't dug in with Wireshark yet, but thought I would just mention my finding.

As an aside, I'm really interested in the development of Python CDDS, as a good python wrapper for DDS would make prototyping and scripting so much faster and easier. Excited to see where the Cyclone implementation goes. That said, compatibility with our existing tools and DDS ecosystem is important to us, so it'd be great to figure out what is causing this disconnect.

**Comment by spiderkeys** [comment]
Another note: haven't yet tried to spin up a reader with the same IDL file using a different implementation to see if discovery/matching happens at that level. Will give that a try soon and report back to see if this is a problem isolated only to the introspection tools.

**Comment by eboasson** [comment]
As aside: I suggest switching to **https://github.com/eclipse/cyclonedds**: I haven't archived the atolab/cdds repository yet, but once the eclipse foundation accepted the code, it was moved to a repository in the eclipse hierarchy. That one is seeing active development.

Your observations are entirely correct 😊

The DCPS and DDSI specifications don't say how to encode type definitions, and of course this resulted in incompatible ways of handling type definitions: RTI had its own system using something suggestive of CORBA type codes (I think TwinOaks and FastRTPS followed their lead); OpenSplice had another system that is even older and is based on XML. As CycloneDDS originates in ADLINK the definition that is output by CycloneDDS is one that OpenSplice understands. Indeed, if you'd look using OpenSplice tooling, the situation would be reversed!

Neither format (but note the past tense in the preceding paragraph, it is there for a reason) is documented. RTI's can be reverse engineered using the Wireshark code, and OpenSplice's can be reverse engineered from the published source code of the OpenSplice CE (or I suppose from the preprocessor of CycloneDDS). Neither ADLINK (formerly PrismTech), nor, I suspect, RTI has a history of reverse engineering other companies code. So this situation has persistent for quite some time

Fortunately this has changed with the XTypes specification. XTypes specifies the type definition format, methods of exchange, everything. However, CycloneDDS doesn't support XTypes yet, but this is high on the to-do list.

**Comment by spiderkeys** [comment]
Thanks for the detailed explanation @eboasson , that makes perfect sense.

I'm excited to see where Cyclone goes, now that this transition from Opensplice has happened and it has the support of the Eclipse Foundation. I think everyone will agree that having more and improved open source support for DDS will be to everyone's benefit!

As per your advice, I will start following the new repo and will be looking forward to X-types support!
